[package]
name = "svox_pico_tts"
version = "0.2.0"
edition = "2021"
description = "Very simple wrapper for the SVOX Pico TTS Linux package"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
